"""Generates high-ticket, publication-ready executive Markdown reports."""
import os
from datetime import datetime
from typing import List
from recovery_agent.models.finding import ClassificationResult, ClassificationStatus


class MarkdownReportGenerator:
    """Renders comprehensive revenue recovery audit reports into outputs/."""

    def __init__(self, output_dir: str = "outputs"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate(
        self, results: List[ClassificationResult], agency_name: str = "Meridian Digital"
    ) -> str:
        timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        filepath = os.path.join(self.output_dir, f"recovery_report_{timestamp_str}.md")

        flagged = [r for r in results if r.status == ClassificationStatus.FLAGGED]
        review = [r for r in results if r.status == ClassificationStatus.REVIEW]
        filtered = [r for r in results if r.status == ClassificationStatus.FILTERED]

        total_flagged_amount = sum(r.recoverable_amount for r in flagged)
        total_flagged_hours = sum(r.billable_hours for r in flagged)

        total_review_amount = sum(r.recoverable_amount for r in review)
        total_review_hours = sum(r.billable_hours for r in review)

        annualized_leak = total_flagged_amount * (52 / 3)  # Extrapolated from 3 weeks

        content = f"""# Executive Revenue Recovery Audit Report
**Agency Client Portfolio**: {agency_name}  
**Audit Period**: August 10, 2026 – August 30, 2026 (3 Weeks)  
**Generated At**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**System**: Autonomous Unbilled Revenue Recovery Agent (Groq / Llama-3.3-70B Grounded)

---

## 1. Executive Summary & Financial Impact

Across the 3-week audited period, our autonomous cross-referencing engine detected **{len(flagged)} confirmed billable revenue leaks** where client work was delivered across Calendar invites, urgent email threads, and Jira tasks but **never entered into timesheets**.

* **Confirmed Recoverable Revenue**: **${total_flagged_amount:,.2f}** ({total_flagged_hours:.1f} billable hours)
* **Under-Review Ambiguous Activities**: **${total_review_amount:,.2f}** ({total_review_hours:.1f} hours)
* **False Positives Guardrailed (Non-billable)**: **{len(filtered)} activities** (Saved $0 in disputed invoices)
* **Projected Annual Revenue Recovery**: **${annualized_leak:,.2f} / year**

> [!IMPORTANT]
> All flagged line items below have been cross-verified against executed client SOW clauses and contain verbatim evidence citations to ensure dispute-free invoice reconciliation.

---

## 2. Confirmed Billable Leaks (Ready for Invoice Dispatch)

| Client | Staff Member | Date | Activity | Hours | Rate | Recoverable | Cited SOW Clause |
|---|---|---|---|---|---|---|---|
"""
        for r in flagged:
            content += (
                f"| **{r.client_name}** | {r.team_member_name} | {r.activity_date} | "
                f"{r.activity_title} | {r.billable_hours:.1f}h | ${r.hourly_rate:.0f}/h | "
                f"**${r.recoverable_amount:,.2f}** | `{r.clause_cited}` |\n"
            )

        content += """
---

## 3. Evidence Grounding & Audit Trace

"""
        for i, r in enumerate(flagged, start=1):
            content += f"""### Finding #{i}: {r.client_name} — ${r.recoverable_amount:,.2f}
- **Date**: {r.activity_date}
- **Staff Contributor**: {r.team_member_name} ({r.billable_hours}h @ ${r.hourly_rate}/hr)
- **Contract Grounding**: `{r.clause_cited}`
- **Reasoning**: {r.reasoning}
- **Evidence Snippet**: 
  > "{r.evidence_snippet}"

"""

        content += f"""---

## 4. Contract-Scope Guardrail Filtration Log (Zero False Positives)

The following activities were scrutinized and **properly excluded** from billing, demonstrating the precision of the 3-stage Contract-Scope Classifier:

| Activity Title | Team Member | Date | Status | Confidence | Guardrail Reasoning |
|---|---|---|---|---|---|
"""
        for r in filtered:
            content += (
                f"| {r.activity_title} | {r.team_member_name} | {r.activity_date} | "
                f"`{r.status.value}` | {r.confidence:.2f} | {r.reasoning} |\n"
            )

        content += """
---
*Report autonomously generated by Crework Unbilled Revenue Recovery Agent.*
"""

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        return filepath
